// CAT-007: Código de Actividad Económica
// Fuente: Ministerio de Hacienda - DGII (Clasificación CIIU Rev. 4)

export interface ActividadEconomica {
    codigo: string;
    descripcion: string;
}

export const actividades: ActividadEconomica[] = [
    // Agricultura, ganadería, silvicultura y pesca (01-03)
    { codigo: "01110", descripcion: "Cultivo de cereales (excepto arroz), legumbres y semillas oleaginosas" },
    { codigo: "01120", descripcion: "Cultivo de arroz" },
    { codigo: "01130", descripcion: "Cultivo de hortalizas y melones, raíces y tubérculos" },
    { codigo: "01140", descripcion: "Cultivo de caña de azúcar" },
    { codigo: "01150", descripcion: "Cultivo de tabaco" },
    { codigo: "01160", descripcion: "Cultivo de plantas de fibra" },
    { codigo: "01191", descripcion: "Cultivo de flores" },
    { codigo: "01192", descripcion: "Cultivo de semillas de hortalizas" },
    { codigo: "01199", descripcion: "Otros cultivos transitorios n.c.p." },
    { codigo: "01210", descripcion: "Cultivo de uva" },
    { codigo: "01220", descripcion: "Cultivo de frutas tropicales y subtropicales" },
    { codigo: "01230", descripcion: "Cultivo de cítricos" },
    { codigo: "01240", descripcion: "Cultivo de frutas de pepita y de hueso" },
    { codigo: "01250", descripcion: "Cultivo de otros frutos y nueces de árboles y arbustos" },
    { codigo: "01260", descripcion: "Cultivo de frutos oleaginosos" },
    { codigo: "01270", descripcion: "Cultivo de plantas con las que se preparan bebidas" },
    { codigo: "01280", descripcion: "Cultivo de especias, plantas aromáticas, medicinales y farmacéuticas" },
    { codigo: "01290", descripcion: "Cultivo de otros productos agrícolas perennes" },
    { codigo: "01301", descripcion: "Propagación de plantas (actividades de los viveros)" },
    { codigo: "01410", descripcion: "Cría de ganado bovino y búfalos" },
    { codigo: "01420", descripcion: "Cría de caballos y otros equinos" },
    { codigo: "01430", descripcion: "Cría de camellos y otros camélidos" },
    { codigo: "01440", descripcion: "Cría de ovejas y cabras" },
    { codigo: "01450", descripcion: "Cría de cerdos" },
    { codigo: "01460", descripcion: "Cría de aves de corral" },
    { codigo: "01490", descripcion: "Cría de otros animales" },
    { codigo: "01500", descripcion: "Explotación mixta (agrícola y pecuaria)" },
    { codigo: "01610", descripcion: "Actividades de apoyo a la agricultura" },
    { codigo: "01620", descripcion: "Actividades de apoyo a la ganadería" },
    { codigo: "01630", descripcion: "Actividades posteriores a la cosecha" },
    { codigo: "01640", descripcion: "Tratamiento de semillas para propagación" },
    { codigo: "01700", descripcion: "Caza ordinaria y mediante trampas y actividades de servicios conexas" },
    { codigo: "02100", descripcion: "Silvicultura y otras actividades forestales" },
    { codigo: "02200", descripcion: "Extracción de madera" },
    { codigo: "02300", descripcion: "Recolección de productos forestales distintos de la madera" },
    { codigo: "02400", descripcion: "Servicios de apoyo a la silvicultura" },
    { codigo: "03110", descripcion: "Pesca marítima" },
    { codigo: "03120", descripcion: "Pesca de agua dulce" },
    { codigo: "03210", descripcion: "Acuicultura marítima" },
    { codigo: "03220", descripcion: "Acuicultura de agua dulce" },

    // Explotación de minas y canteras (05-09)
    { codigo: "05100", descripcion: "Extracción de carbón de piedra" },
    { codigo: "05200", descripcion: "Extracción de lignito" },
    { codigo: "06100", descripcion: "Extracción de petróleo crudo" },
    { codigo: "06200", descripcion: "Extracción de gas natural" },
    { codigo: "07100", descripcion: "Extracción de minerales de hierro" },
    { codigo: "07210", descripcion: "Extracción de minerales de uranio y torio" },
    { codigo: "07290", descripcion: "Extracción de otros minerales metalíferos no ferrosos" },
    { codigo: "08100", descripcion: "Extracción de piedra, arena y arcilla" },
    { codigo: "08910", descripcion: "Extracción de minerales para la fabricación de abonos y productos químicos" },
    { codigo: "08920", descripcion: "Extracción de turba" },
    { codigo: "08930", descripcion: "Extracción de sal" },
    { codigo: "08990", descripcion: "Explotación de otras minas y canteras n.c.p." },
    { codigo: "09100", descripcion: "Actividades de apoyo para la extracción de petróleo y gas natural" },
    { codigo: "09900", descripcion: "Actividades de apoyo para otras actividades de explotación de minas y canteras" },

    // Industrias manufactureras (10-33)
    { codigo: "10101", descripcion: "Matanza de ganado y aves" },
    { codigo: "10102", descripcion: "Preparación de carnes" },
    { codigo: "10200", descripcion: "Procesamiento y conservación de pescados, crustáceos y moluscos" },
    { codigo: "10301", descripcion: "Procesamiento y conservación de frutas" },
    { codigo: "10302", descripcion: "Procesamiento y conservación de legumbres y hortalizas" },
    { codigo: "10400", descripcion: "Elaboración de aceites y grasas de origen vegetal y animal" },
    { codigo: "10501", descripcion: "Elaboración de productos lácteos" },
    { codigo: "10502", descripcion: "Elaboración de helados" },
    { codigo: "10611", descripcion: "Trilla de granos" },
    { codigo: "10612", descripcion: "Elaboración de productos de molinería" },
    { codigo: "10620", descripcion: "Elaboración de almidones y productos derivados del almidón" },
    { codigo: "10710", descripcion: "Elaboración de productos de panadería" },
    { codigo: "10720", descripcion: "Elaboración de azúcar" },
    { codigo: "10730", descripcion: "Elaboración de cacao y chocolate y de productos de confitería" },
    { codigo: "10740", descripcion: "Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares" },
    { codigo: "10750", descripcion: "Elaboración de comidas y platos preparados" },
    { codigo: "10790", descripcion: "Elaboración de otros productos alimenticios n.c.p." },
    { codigo: "10800", descripcion: "Elaboración de piensos preparados para animales" },
    { codigo: "11010", descripcion: "Destilación, rectificación y mezcla de bebidas alcohólicas" },
    { codigo: "11020", descripcion: "Elaboración de vinos" },
    { codigo: "11030", descripcion: "Elaboración de bebidas malteadas y de malta" },
    { codigo: "11040", descripcion: "Elaboración de bebidas no alcohólicas; producción de aguas minerales" },
    { codigo: "12000", descripcion: "Elaboración de productos de tabaco" },
    { codigo: "13100", descripcion: "Preparación e hilatura de fibras textiles" },
    { codigo: "13200", descripcion: "Tejedura de productos textiles" },
    { codigo: "13300", descripcion: "Acabado de productos textiles" },
    { codigo: "13910", descripcion: "Fabricación de tejidos de punto y ganchillo" },
    { codigo: "13920", descripcion: "Fabricación de artículos confeccionados de materiales textiles, excepto prendas de vestir" },
    { codigo: "13930", descripcion: "Fabricación de tapices y alfombras" },
    { codigo: "13940", descripcion: "Fabricación de cuerdas, cordeles, bramantes y redes" },
    { codigo: "13990", descripcion: "Fabricación de otros productos textiles n.c.p." },
    { codigo: "14100", descripcion: "Fabricación de prendas de vestir, excepto prendas de piel" },
    { codigo: "14200", descripcion: "Fabricación de artículos de piel" },
    { codigo: "14300", descripcion: "Fabricación de artículos de punto y ganchillo" },
    { codigo: "15110", descripcion: "Curtido y adobo de cueros; adobo y teñido de pieles" },
    { codigo: "15120", descripcion: "Fabricación de maletas, bolsos de mano, artículos de talabartería y guarnicionería" },
    { codigo: "15200", descripcion: "Fabricación de calzado" },
    { codigo: "16100", descripcion: "Aserrado y acepilladura de madera" },
    { codigo: "16210", descripcion: "Fabricación de hojas de madera para enchapado y tableros" },
    { codigo: "16220", descripcion: "Fabricación de partes y piezas de carpintería para edificios y construcciones" },
    { codigo: "16230", descripcion: "Fabricación de recipientes de madera" },
    { codigo: "16290", descripcion: "Fabricación de otros productos de madera; fabricación de artículos de corcho, paja y materiales trenzables" },
    { codigo: "17010", descripcion: "Fabricación de pasta de madera, papel y cartón" },
    { codigo: "17020", descripcion: "Fabricación de papel y cartón ondulado y de envases de papel y cartón" },
    { codigo: "17090", descripcion: "Fabricación de otros artículos de papel y cartón" },
    { codigo: "18110", descripcion: "Impresión" },
    { codigo: "18120", descripcion: "Actividades de servicios relacionados con la impresión" },
    { codigo: "18200", descripcion: "Reproducción de grabaciones" },
    { codigo: "19100", descripcion: "Fabricación de productos de hornos de coque" },
    { codigo: "19200", descripcion: "Fabricación de productos de la refinación del petróleo" },
    { codigo: "20110", descripcion: "Fabricación de sustancias químicas básicas" },
    { codigo: "20120", descripcion: "Fabricación de abonos y compuestos de nitrógeno" },
    { codigo: "20130", descripcion: "Fabricación de plásticos y caucho sintético en formas primarias" },
    { codigo: "20210", descripcion: "Fabricación de plaguicidas y otros productos químicos de uso agropecuario" },
    { codigo: "20220", descripcion: "Fabricación de pinturas, barnices y productos de revestimiento similares" },
    { codigo: "20230", descripcion: "Fabricación de jabones y detergentes, preparados para limpiar, perfumes y preparados de tocador" },
    { codigo: "20290", descripcion: "Fabricación de otros productos químicos n.c.p." },
    { codigo: "20300", descripcion: "Fabricación de fibras artificiales" },
    { codigo: "21000", descripcion: "Fabricación de productos farmacéuticos, sustancias químicas medicinales" },
    { codigo: "22110", descripcion: "Fabricación de cubiertas y cámaras de caucho; recauchutado y renovación de cubiertas" },
    { codigo: "22190", descripcion: "Fabricación de otros productos de caucho" },
    { codigo: "22200", descripcion: "Fabricación de productos de plástico" },
    { codigo: "23100", descripcion: "Fabricación de vidrio y productos de vidrio" },
    { codigo: "23910", descripcion: "Fabricación de productos refractarios" },
    { codigo: "23920", descripcion: "Fabricación de materiales de arcilla para la construcción" },
    { codigo: "23930", descripcion: "Fabricación de otros productos de porcelana y de cerámica" },
    { codigo: "23940", descripcion: "Fabricación de cemite, cal y yeso" },
    { codigo: "23950", descripcion: "Fabricación de artículos de hormigón, cemento y yeso" },
    { codigo: "23960", descripcion: "Corte, talla y acabado de la piedra" },
    { codigo: "23990", descripcion: "Fabricación de otros productos minerales no metálicos n.c.p." },
    { codigo: "24100", descripcion: "Industrias básicas de hierro y acero" },
    { codigo: "24200", descripcion: "Fabricación de productos primarios de metales preciosos y otros metales no ferrosos" },
    { codigo: "24310", descripcion: "Fundición de hierro y acero" },
    { codigo: "24320", descripcion: "Fundición de metales no ferrosos" },
    { codigo: "25110", descripcion: "Fabricación de productos metálicos para uso estructural" },
    { codigo: "25120", descripcion: "Fabricación de tanques, depósitos y recipientes de metal" },
    { codigo: "25130", descripcion: "Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central" },
    { codigo: "25200", descripcion: "Fabricación de armas y municiones" },
    { codigo: "25910", descripcion: "Forja, prensado, estampado y laminado de metales; pulvimetalurgia" },
    { codigo: "25920", descripcion: "Tratamiento y revestimiento de metales; maquinado" },
    { codigo: "25930", descripcion: "Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería" },
    { codigo: "25990", descripcion: "Fabricación de otros productos elaborados de metal n.c.p." },
    { codigo: "26100", descripcion: "Fabricación de componentes y tableros electrónicos" },
    { codigo: "26200", descripcion: "Fabricación de ordenadores y equipo periférico" },
    { codigo: "26300", descripcion: "Fabricación de equipo de comunicaciones" },
    { codigo: "26400", descripcion: "Fabricación de aparatos electrónicos de consumo" },
    { codigo: "26510", descripcion: "Fabricación de equipo de medición, prueba, navegación y control" },
    { codigo: "26520", descripcion: "Fabricación de relojes" },
    { codigo: "26600", descripcion: "Fabricación de equipo de irradiación y equipo electrónico de uso médico y terapéutico" },
    { codigo: "26700", descripcion: "Fabricación de instrumentos ópticos y equipo fotográfico" },
    { codigo: "26800", descripcion: "Fabricación de soportes magnéticos y ópticos" },
    { codigo: "27100", descripcion: "Fabricación de motores, generadores y transformadores eléctricos" },
    { codigo: "27200", descripcion: "Fabricación de pilas, baterías y acumuladores" },
    { codigo: "27310", descripcion: "Fabricación de cables de fibra óptica" },
    { codigo: "27320", descripcion: "Fabricación de otros hilos y cables eléctricos" },
    { codigo: "27330", descripcion: "Fabricación de dispositivos de cableado" },
    { codigo: "27400", descripcion: "Fabricación de equipo eléctrico de iluminación" },
    { codigo: "27500", descripcion: "Fabricación de aparatos de uso doméstico" },
    { codigo: "27900", descripcion: "Fabricación de otros tipos de equipo eléctrico" },
    { codigo: "28110", descripcion: "Fabricación de motores y turbinas, excepto motores para aeronaves, vehículos automotores y motocicletas" },
    { codigo: "28120", descripcion: "Fabricación de equipo de propulsión de fluidos" },
    { codigo: "28130", descripcion: "Fabricación de otras bombas, compresores, grifos y válvulas" },
    { codigo: "28140", descripcion: "Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión" },
    { codigo: "28150", descripcion: "Fabricación de hornos, hogares y quemadores" },
    { codigo: "28160", descripcion: "Fabricación de equipo de elevación y manipulación" },
    { codigo: "28170", descripcion: "Fabricación de maquinaria y equipo de oficina (excepto ordenadores y equipo periférico)" },
    { codigo: "28180", descripcion: "Fabricación de herramientas de mano motorizadas" },
    { codigo: "28190", descripcion: "Fabricación de otros tipos de maquinaria de uso general" },
    { codigo: "28210", descripcion: "Fabricación de maquinaria agropecuaria y forestal" },
    { codigo: "28220", descripcion: "Fabricación de maquinaria para la conformación de metales y de máquinas herramienta" },
    { codigo: "28230", descripcion: "Fabricación de maquinaria metalúrgica" },
    { codigo: "28240", descripcion: "Fabricación de maquinaria para la explotación de minas y canteras y para obras de construcción" },
    { codigo: "28250", descripcion: "Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco" },
    { codigo: "28260", descripcion: "Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros" },
    { codigo: "28290", descripcion: "Fabricación de otros tipos de maquinaria de uso especial" },
    { codigo: "29100", descripcion: "Fabricación de vehículos automotores" },
    { codigo: "29200", descripcion: "Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semirremolques" },
    { codigo: "29300", descripcion: "Fabricación de partes, piezas y accesorios para vehículos automotores" },
    { codigo: "30110", descripcion: "Construcción de buques y estructuras flotantes" },
    { codigo: "30120", descripcion: "Construcción de embarcaciones de recreo y de deporte" },
    { codigo: "30200", descripcion: "Fabricación de locomotoras y material rodante" },
    { codigo: "30300", descripcion: "Fabricación de aeronaves, naves espaciales y maquinaria conexa" },
    { codigo: "30400", descripcion: "Fabricación de vehículos militares de combate" },
    { codigo: "30910", descripcion: "Fabricación de motocicletas" },
    { codigo: "30920", descripcion: "Fabricación de bicicletas y de sillones de ruedas para inválidos" },
    { codigo: "30990", descripcion: "Fabricación de otros tipos de equipo de transporte n.c.p." },
    { codigo: "31000", descripcion: "Fabricación de muebles" },
    { codigo: "32110", descripcion: "Fabricación de joyas y artículos conexos" },
    { codigo: "32120", descripcion: "Fabricación de bisutería y artículos conexos" },
    { codigo: "32200", descripcion: "Fabricación de instrumentos musicales" },
    { codigo: "32300", descripcion: "Fabricación de artículos de deporte" },
    { codigo: "32400", descripcion: "Fabricación de juegos y juguetes" },
    { codigo: "32500", descripcion: "Fabricación de instrumentos y materiales médicos y odontológicos" },
    { codigo: "32900", descripcion: "Otras industrias manufactureras n.c.p." },
    { codigo: "33110", descripcion: "Reparación de productos elaborados de metal" },
    { codigo: "33120", descripcion: "Reparación de maquinaria" },
    { codigo: "33130", descripcion: "Reparación de equipo electrónico y óptico" },
    { codigo: "33140", descripcion: "Reparación de equipo eléctrico" },
    { codigo: "33150", descripcion: "Reparación de equipo de transporte, excepto vehículos automotores" },
    { codigo: "33190", descripcion: "Reparación de otros tipos de equipo" },
    { codigo: "33200", descripcion: "Instalación de maquinaria y equipo industriales" },

    // Suministro de electricidad, gas, vapor y aire acondicionado (35)
    { codigo: "35101", descripcion: "Generación de energía eléctrica" },
    { codigo: "35102", descripcion: "Transmisión de energía eléctrica" },
    { codigo: "35103", descripcion: "Distribución de energía eléctrica" },
    { codigo: "35200", descripcion: "Fabricación de gas; distribución de combustibles gaseosos por tuberías" },
    { codigo: "35300", descripcion: "Suministro de vapor y de aire acondicionado" },

    // Suministro de agua; evacuación de aguas residuales (36-39)
    { codigo: "36000", descripcion: "Captación, tratamiento y distribución de agua" },
    { codigo: "37000", descripcion: "Evacuación de aguas residuales" },
    { codigo: "38110", descripcion: "Recogida de desechos no peligrosos" },
    { codigo: "38120", descripcion: "Recogida de desechos peligrosos" },
    { codigo: "38210", descripcion: "Tratamiento y eliminación de desechos no peligrosos" },
    { codigo: "38220", descripcion: "Tratamiento y eliminación de desechos peligrosos" },
    { codigo: "38300", descripcion: "Recuperación de materiales" },
    { codigo: "39000", descripcion: "Actividades de descontaminación y otros servicios de gestión de desechos" },

    // Construcción (41-43)
    { codigo: "41001", descripcion: "Construcción de edificios residenciales" },
    { codigo: "41002", descripcion: "Construcción de edificios no residenciales" },
    { codigo: "42100", descripcion: "Construcción de carreteras y líneas de ferrocarril" },
    { codigo: "42200", descripcion: "Construcción de proyectos de servicio público" },
    { codigo: "42900", descripcion: "Construcción de otras obras de ingeniería civil" },
    { codigo: "43110", descripcion: "Demolición" },
    { codigo: "43120", descripcion: "Preparación del terreno" },
    { codigo: "43210", descripcion: "Instalaciones eléctricas" },
    { codigo: "43220", descripcion: "Instalaciones de fontanería, calefacción y aire acondicionado" },
    { codigo: "43290", descripcion: "Otras instalaciones para obras de construcción" },
    { codigo: "43300", descripcion: "Terminación y acabado de edificios" },
    { codigo: "43900", descripcion: "Otras actividades especializadas de construcción" },

    // Comercio al por mayor y al por menor (45-47)
    { codigo: "45101", descripcion: "Venta de vehículos automotores nuevos" },
    { codigo: "45102", descripcion: "Venta de vehículos automotores usados" },
    { codigo: "45200", descripcion: "Mantenimiento y reparación de vehículos automotores" },
    { codigo: "45300", descripcion: "Venta de partes, piezas y accesorios para vehículos automotores" },
    { codigo: "45400", descripcion: "Venta, mantenimiento y reparación de motocicletas y de sus partes, piezas y accesorios" },
    { codigo: "46100", descripcion: "Venta al por mayor a cambio de una comisión o por contrata" },
    { codigo: "46210", descripcion: "Venta al por mayor de materias primas agropecuarias y animales vivos" },
    { codigo: "46220", descripcion: "Venta al por mayor de alimentos, bebidas y tabaco" },
    { codigo: "46310", descripcion: "Venta al por mayor de productos textiles, prendas de vestir y calzado" },
    { codigo: "46320", descripcion: "Venta al por mayor de otros enseres domésticos" },
    { codigo: "46410", descripcion: "Venta al por mayor de productos textiles" },
    { codigo: "46420", descripcion: "Venta al por mayor de prendas de vestir y calzado" },
    { codigo: "46430", descripcion: "Venta al por mayor de aparatos y equipo de uso doméstico" },
    { codigo: "46491", descripcion: "Venta al por mayor de artículos de papelería, libros, revistas y periódicos" },
    { codigo: "46492", descripcion: "Venta al por mayor de productos farmacéuticos" },
    { codigo: "46493", descripcion: "Venta al por mayor de artículos de perfumería y de tocador" },
    { codigo: "46499", descripcion: "Venta al por mayor de otros enseres domésticos n.c.p." },
    { codigo: "46510", descripcion: "Venta al por mayor de ordenadores, equipo periférico y programas informáticos" },
    { codigo: "46520", descripcion: "Venta al por mayor de equipo, partes y piezas electrónicos y de telecomunicaciones" },
    { codigo: "46530", descripcion: "Venta al por mayor de maquinaria, equipo y materiales agropecuarios" },
    { codigo: "46590", descripcion: "Venta al por mayor de otros tipos de maquinaria y equipo" },
    { codigo: "46610", descripcion: "Venta al por mayor de combustibles sólidos, líquidos y gaseosos y productos conexos" },
    { codigo: "46620", descripcion: "Venta al por mayor de metales y minerales metalíferos" },
    { codigo: "46630", descripcion: "Venta al por mayor de materiales de construcción, artículos de ferretería y equipo y materiales de fontanería y calefacción" },
    { codigo: "46690", descripcion: "Venta al por mayor de desperdicios, desechos, chatarra y otros productos n.c.p." },
    { codigo: "46900", descripcion: "Venta al por mayor no especializada" },
    { codigo: "47111", descripcion: "Venta al por menor en supermercados" },
    { codigo: "47112", descripcion: "Venta al por menor en tiendas de conveniencia" },
    { codigo: "47190", descripcion: "Otras actividades de venta al por menor en comercios no especializados" },
    { codigo: "47210", descripcion: "Venta al por menor de alimentos en comercios especializados" },
    { codigo: "47220", descripcion: "Venta al por menor de bebidas en comercios especializados" },
    { codigo: "47230", descripcion: "Venta al por menor de productos de tabaco en comercios especializados" },
    { codigo: "47300", descripcion: "Venta al por menor de combustibles para vehículos automotores en comercios especializados" },
    { codigo: "47410", descripcion: "Venta al por menor de ordenadores, equipo periférico, programas informáticos y equipo de telecomunicaciones" },
    { codigo: "47420", descripcion: "Venta al por menor de equipo de sonido y de vídeo en comercios especializados" },
    { codigo: "47510", descripcion: "Venta al por menor de productos textiles en comercios especializados" },
    { codigo: "47520", descripcion: "Venta al por menor de artículos de ferretería, pinturas y productos de vidrio" },
    { codigo: "47530", descripcion: "Venta al por menor de tapices, alfombras y cubrimientos para paredes y pisos" },
    { codigo: "47591", descripcion: "Venta al por menor de muebles" },
    { codigo: "47592", descripcion: "Venta al por menor de aparatos eléctricos de uso doméstico" },
    { codigo: "47593", descripcion: "Venta al por menor de utensilios domésticos, cuchillería y vajilla" },
    { codigo: "47599", descripcion: "Venta al por menor de otros artículos de uso doméstico n.c.p." },
    { codigo: "47610", descripcion: "Venta al por menor de libros, periódicos y artículos de papelería" },
    { codigo: "47620", descripcion: "Venta al por menor de grabaciones de música y de vídeo en comercios especializados" },
    { codigo: "47630", descripcion: "Venta al por menor de equipo de deporte en comercios especializados" },
    { codigo: "47640", descripcion: "Venta al por menor de juegos y juguetes en comercios especializados" },
    { codigo: "47711", descripcion: "Venta al por menor de prendas de vestir y calzado" },
    { codigo: "47712", descripcion: "Venta al por menor de productos de cuero" },
    { codigo: "47720", descripcion: "Venta al por menor de productos farmacéuticos y medicinales, cosméticos y artículos de tocador" },
    { codigo: "47730", descripcion: "Venta al por menor de otros productos nuevos en comercios especializados" },
    { codigo: "47741", descripcion: "Venta al por menor de antigüedades" },
    { codigo: "47742", descripcion: "Venta al por menor de ropa usada" },
    { codigo: "47749", descripcion: "Venta al por menor de otros artículos de segunda mano" },
    { codigo: "47810", descripcion: "Venta al por menor de alimentos, bebidas y tabaco en puestos de venta y mercados" },
    { codigo: "47820", descripcion: "Venta al por menor de productos textiles, prendas de vestir y calzado en puestos de venta y mercados" },
    { codigo: "47890", descripcion: "Venta al por menor de otros productos en puestos de venta y mercados" },
    { codigo: "47910", descripcion: "Venta al por menor por correo y por Internet" },
    { codigo: "47990", descripcion: "Otras actividades de venta al por menor no realizadas en comercios, puestos de venta o mercados" },

    // Transporte y almacenamiento (49-53)
    { codigo: "49110", descripcion: "Transporte interurbano de pasajeros por ferrocarril" },
    { codigo: "49120", descripcion: "Transporte de carga por ferrocarril" },
    { codigo: "49211", descripcion: "Transporte urbano colectivo regular de pasajeros" },
    { codigo: "49212", descripcion: "Servicio de taxi" },
    { codigo: "49221", descripcion: "Transporte interurbano de pasajeros" },
    { codigo: "49222", descripcion: "Transporte internacional de pasajeros" },
    { codigo: "49230", descripcion: "Transporte de carga por carretera" },
    { codigo: "49300", descripcion: "Transporte por tuberías" },
    { codigo: "50110", descripcion: "Transporte de pasajeros marítimo y de cabotaje" },
    { codigo: "50120", descripcion: "Transporte de carga marítimo y de cabotaje" },
    { codigo: "50210", descripcion: "Transporte de pasajeros por vías de navegación interiores" },
    { codigo: "50220", descripcion: "Transporte de carga por vías de navegación interiores" },
    { codigo: "51100", descripcion: "Transporte de pasajeros por vía aérea" },
    { codigo: "51200", descripcion: "Transporte de carga por vía aérea" },
    { codigo: "52100", descripcion: "Almacenamiento y depósito" },
    { codigo: "52211", descripcion: "Explotación de terminales terrestres de pasajeros" },
    { codigo: "52212", descripcion: "Actividades de servicios vinculadas al transporte terrestre n.c.p." },
    { codigo: "52220", descripcion: "Actividades de servicios vinculadas al transporte acuático" },
    { codigo: "52230", descripcion: "Actividades de servicios vinculadas al transporte aéreo" },
    { codigo: "52240", descripcion: "Manipulación de la carga" },
    { codigo: "52290", descripcion: "Otras actividades de apoyo al transporte" },
    { codigo: "53100", descripcion: "Actividades postales" },
    { codigo: "53200", descripcion: "Actividades de mensajería" },

    // Alojamiento y servicios de comida (55-56)
    { codigo: "55101", descripcion: "Hoteles" },
    { codigo: "55102", descripcion: "Moteles" },
    { codigo: "55103", descripcion: "Apartamentos turísticos" },
    { codigo: "55104", descripcion: "Casas de huéspedes" },
    { codigo: "55109", descripcion: "Otros tipos de alojamiento para estancias cortas" },
    { codigo: "55200", descripcion: "Actividades de campamentos, parques de vehículos recreativos y parques de caravanas" },
    { codigo: "55900", descripcion: "Otras actividades de alojamiento" },
    { codigo: "56101", descripcion: "Restaurantes" },
    { codigo: "56102", descripcion: "Cafeterías" },
    { codigo: "56103", descripcion: "Comida rápida" },
    { codigo: "56104", descripcion: "Venta de comida preparada o para llevar" },
    { codigo: "56210", descripcion: "Suministro de comidas por encargo" },
    { codigo: "56290", descripcion: "Otras actividades de servicio de comidas" },
    { codigo: "56301", descripcion: "Bares" },
    { codigo: "56302", descripcion: "Discotecas" },
    { codigo: "56309", descripcion: "Otros servicios de bebidas" },

    // Información y comunicaciones (58-63)
    { codigo: "58110", descripcion: "Edición de libros" },
    { codigo: "58120", descripcion: "Edición de directorios y listas de correo" },
    { codigo: "58130", descripcion: "Edición de periódicos, revistas y otras publicaciones periódicas" },
    { codigo: "58190", descripcion: "Otras actividades de edición" },
    { codigo: "58200", descripcion: "Edición de programas informáticos" },
    { codigo: "59110", descripcion: "Actividades de producción de películas cinematográficas, vídeos y programas de televisión" },
    { codigo: "59120", descripcion: "Actividades de postproducción de películas cinematográficas, vídeos y programas de televisión" },
    { codigo: "59130", descripcion: "Actividades de distribución de películas cinematográficas, vídeos y programas de televisión" },
    { codigo: "59140", descripcion: "Actividades de exhibición de películas cinematográficas" },
    { codigo: "59200", descripcion: "Actividades de grabación de sonido y edición de música" },
    { codigo: "60100", descripcion: "Transmisiones de radio" },
    { codigo: "60200", descripcion: "Programación y transmisiones de televisión" },
    { codigo: "61100", descripcion: "Actividades de telecomunicaciones alámbricas" },
    { codigo: "61200", descripcion: "Actividades de telecomunicaciones inalámbricas" },
    { codigo: "61300", descripcion: "Actividades de telecomunicaciones por satélite" },
    { codigo: "61900", descripcion: "Otras actividades de telecomunicaciones" },
    { codigo: "62010", descripcion: "Programación informática" },
    { codigo: "62020", descripcion: "Consultoría de informática y gestión de instalaciones informáticas" },
    { codigo: "62090", descripcion: "Otras actividades de tecnología de la información y de servicios informáticos" },
    { codigo: "63110", descripcion: "Procesamiento de datos, hospedaje y actividades conexas" },
    { codigo: "63120", descripcion: "Portales web" },
    { codigo: "63910", descripcion: "Actividades de agencias de noticias" },
    { codigo: "63990", descripcion: "Otras actividades de servicios de información n.c.p." },

    // Actividades financieras y de seguros (64-66)
    { codigo: "64110", descripcion: "Banca central" },
    { codigo: "64191", descripcion: "Bancos" },
    { codigo: "64192", descripcion: "Sociedades de ahorro y crédito" },
    { codigo: "64199", descripcion: "Otras actividades de intermediación monetaria" },
    { codigo: "64200", descripcion: "Actividades de sociedades de cartera" },
    { codigo: "64300", descripcion: "Fondos y sociedades de inversión y entidades financieras similares" },
    { codigo: "64910", descripcion: "Arrendamiento financiero" },
    { codigo: "64920", descripcion: "Otras actividades de concesión de crédito" },
    { codigo: "64990", descripcion: "Otras actividades de servicios financieros, excepto las de seguros y fondos de pensiones" },
    { codigo: "65110", descripcion: "Seguros de vida" },
    { codigo: "65120", descripcion: "Seguros generales" },
    { codigo: "65200", descripcion: "Reaseguros" },
    { codigo: "65300", descripcion: "Fondos de pensiones" },
    { codigo: "66110", descripcion: "Administración de mercados financieros" },
    { codigo: "66120", descripcion: "Corretaje de valores y de contratos de productos básicos" },
    { codigo: "66190", descripcion: "Otras actividades auxiliares de las actividades de servicios financieros" },
    { codigo: "66210", descripcion: "Evaluación de riesgos y daños" },
    { codigo: "66220", descripcion: "Actividades de agentes y corredores de seguros" },
    { codigo: "66290", descripcion: "Otras actividades auxiliares de las actividades de seguros y fondos de pensiones" },
    { codigo: "66300", descripcion: "Actividades de gestión de fondos" },

    // Actividades inmobiliarias (68)
    { codigo: "68100", descripcion: "Actividades inmobiliarias realizadas con bienes propios o arrendados" },
    { codigo: "68200", descripcion: "Actividades inmobiliarias realizadas a cambio de una retribución o por contrata" },

    // Actividades profesionales, científicas y técnicas (69-75)
    { codigo: "69100", descripcion: "Actividades jurídicas" },
    { codigo: "69200", descripcion: "Actividades de contabilidad, teneduría de libros y auditoría; consultoría fiscal" },
    { codigo: "70100", descripcion: "Actividades de oficinas principales" },
    { codigo: "70200", descripcion: "Actividades de consultoría de gestión" },
    { codigo: "71100", descripcion: "Actividades de arquitectura e ingeniería y actividades conexas de consultoría técnica" },
    { codigo: "71200", descripcion: "Ensayos y análisis técnicos" },
    { codigo: "72100", descripcion: "Investigación y desarrollo experimental en el campo de las ciencias naturales y la ingeniería" },
    { codigo: "72200", descripcion: "Investigación y desarrollo experimental en el campo de las ciencias sociales y las humanidades" },
    { codigo: "73100", descripcion: "Publicidad" },
    { codigo: "73200", descripcion: "Estudios de mercado y encuestas de opinión pública" },
    { codigo: "74100", descripcion: "Actividades especializadas de diseño" },
    { codigo: "74200", descripcion: "Actividades de fotografía" },
    { codigo: "74900", descripcion: "Otras actividades profesionales, científicas y técnicas n.c.p." },
    { codigo: "75000", descripcion: "Actividades veterinarias" },

    // Actividades de servicios administrativos y de apoyo (77-82)
    { codigo: "77100", descripcion: "Alquiler de vehículos automotores" },
    { codigo: "77210", descripcion: "Alquiler de equipo recreativo y deportivo" },
    { codigo: "77220", descripcion: "Alquiler de cintas de vídeo y discos" },
    { codigo: "77290", descripcion: "Alquiler de otros efectos personales y enseres domésticos" },
    { codigo: "77310", descripcion: "Alquiler de maquinaria y equipo agropecuario" },
    { codigo: "77320", descripcion: "Alquiler de maquinaria y equipo para la construcción" },
    { codigo: "77330", descripcion: "Alquiler de maquinaria y equipo de oficina" },
    { codigo: "77340", descripcion: "Alquiler de equipo de transporte acuático" },
    { codigo: "77350", descripcion: "Alquiler de equipo de transporte aéreo" },
    { codigo: "77390", descripcion: "Alquiler de otros tipos de maquinaria, equipo y bienes tangibles" },
    { codigo: "77400", descripcion: "Arrendamiento de propiedad intelectual y productos similares, excepto obras protegidas por derechos de autor" },
    { codigo: "78100", descripcion: "Actividades de agencias de empleo" },
    { codigo: "78200", descripcion: "Actividades de agencias de empleo temporal" },
    { codigo: "78300", descripcion: "Otras actividades de dotación de recursos humanos" },
    { codigo: "79110", descripcion: "Actividades de agencias de viajes" },
    { codigo: "79120", descripcion: "Actividades de operadores turísticos" },
    { codigo: "79900", descripcion: "Otros servicios de reservas y actividades conexas" },
    { codigo: "80100", descripcion: "Actividades de seguridad privada" },
    { codigo: "80200", descripcion: "Actividades de servicios de sistemas de seguridad" },
    { codigo: "80300", descripcion: "Actividades de investigación" },
    { codigo: "81100", descripcion: "Actividades combinadas de apoyo a instalaciones" },
    { codigo: "81210", descripcion: "Limpieza general de edificios" },
    { codigo: "81290", descripcion: "Otras actividades de limpieza de edificios e instalaciones industriales" },
    { codigo: "81300", descripcion: "Actividades de paisajismo y servicios de mantenimiento conexos" },
    { codigo: "82110", descripcion: "Actividades combinadas de servicios administrativos de oficina" },
    { codigo: "82190", descripcion: "Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo de oficina" },
    { codigo: "82200", descripcion: "Actividades de centros de llamadas" },
    { codigo: "82300", descripcion: "Organización de convenciones y exposiciones comerciales" },
    { codigo: "82910", descripcion: "Actividades de agencias de cobro y agencias de calificación crediticia" },
    { codigo: "82920", descripcion: "Actividades de envasado y empaquetado" },
    { codigo: "82990", descripcion: "Otras actividades de servicios de apoyo a las empresas n.c.p." },

    // Administración pública y defensa (84)
    { codigo: "84110", descripcion: "Actividades de la administración pública en general" },
    { codigo: "84120", descripcion: "Regulación de las actividades de organismos que prestan servicios sanitarios, educativos, culturales y otros servicios sociales" },
    { codigo: "84130", descripcion: "Regulación y facilitación de la actividad económica" },
    { codigo: "84210", descripcion: "Relaciones exteriores" },
    { codigo: "84220", descripcion: "Actividades de defensa" },
    { codigo: "84230", descripcion: "Actividades de mantenimiento del orden público y de seguridad" },
    { codigo: "84300", descripcion: "Actividades de planes de seguridad social de afiliación obligatoria" },

    // Enseñanza (85)
    { codigo: "85100", descripcion: "Enseñanza preescolar y primaria" },
    { codigo: "85210", descripcion: "Enseñanza secundaria de formación general" },
    { codigo: "85220", descripcion: "Enseñanza secundaria de formación técnica y profesional" },
    { codigo: "85300", descripcion: "Enseñanza superior" },
    { codigo: "85410", descripcion: "Enseñanza deportiva y recreativa" },
    { codigo: "85420", descripcion: "Enseñanza cultural" },
    { codigo: "85490", descripcion: "Otros tipos de enseñanza" },
    { codigo: "85500", descripcion: "Actividades de apoyo a la enseñanza" },

    // Actividades de atención de la salud humana y de asistencia social (86-88)
    { codigo: "86100", descripcion: "Actividades de hospitales" },
    { codigo: "86201", descripcion: "Actividades de médicos" },
    { codigo: "86202", descripcion: "Actividades de odontólogos" },
    { codigo: "86901", descripcion: "Actividades de laboratorios" },
    { codigo: "86909", descripcion: "Otras actividades de atención de la salud humana" },
    { codigo: "87100", descripcion: "Actividades de atención de enfermería en instituciones" },
    { codigo: "87200", descripcion: "Actividades de atención en instituciones para personas con retraso mental, enfermos mentales y toxicómanos" },
    { codigo: "87300", descripcion: "Actividades de atención en instituciones para personas de edad y personas con discapacidad" },
    { codigo: "87900", descripcion: "Otras actividades de atención en instituciones" },
    { codigo: "88100", descripcion: "Actividades de asistencia social sin alojamiento para personas de edad y personas con discapacidad" },
    { codigo: "88900", descripcion: "Otras actividades de asistencia social sin alojamiento" },

    // Actividades artísticas, de entretenimiento y recreativas (90-93)
    { codigo: "90000", descripcion: "Actividades creativas, artísticas y de entretenimiento" },
    { codigo: "91010", descripcion: "Actividades de bibliotecas y archivos" },
    { codigo: "91020", descripcion: "Actividades de museos y gestión de lugares y edificios históricos" },
    { codigo: "91030", descripcion: "Actividades de jardines botánicos, zoológicos y reservas naturales" },
    { codigo: "92000", descripcion: "Actividades de juegos de azar y apuestas" },
    { codigo: "93110", descripcion: "Gestión de instalaciones deportivas" },
    { codigo: "93120", descripcion: "Actividades de clubes deportivos" },
    { codigo: "93190", descripcion: "Otras actividades deportivas" },
    { codigo: "93210", descripcion: "Actividades de parques de atracciones y parques temáticos" },
    { codigo: "93290", descripcion: "Otras actividades de esparcimiento y recreativas" },

    // Otras actividades de servicios (94-96)
    { codigo: "94110", descripcion: "Actividades de asociaciones empresariales y de empleadores" },
    { codigo: "94120", descripcion: "Actividades de asociaciones profesionales" },
    { codigo: "94200", descripcion: "Actividades de sindicatos" },
    { codigo: "94910", descripcion: "Actividades de organizaciones religiosas" },
    { codigo: "94920", descripcion: "Actividades de organizaciones políticas" },
    { codigo: "94990", descripcion: "Actividades de otras asociaciones n.c.p." },
    { codigo: "95110", descripcion: "Reparación de ordenadores y equipo periférico" },
    { codigo: "95120", descripcion: "Reparación de equipo de comunicaciones" },
    { codigo: "95210", descripcion: "Reparación de aparatos electrónicos de consumo" },
    { codigo: "95220", descripcion: "Reparación de aparatos de uso doméstico y equipo doméstico y de jardinería" },
    { codigo: "95230", descripcion: "Reparación de calzado y de artículos de cuero" },
    { codigo: "95240", descripcion: "Reparación de muebles y accesorios domésticos" },
    { codigo: "95290", descripcion: "Reparación de otros efectos personales y enseres domésticos" },
    { codigo: "96010", descripcion: "Lavado y limpieza, incluida la limpieza en seco, de productos textiles y de piel" },
    { codigo: "96020", descripcion: "Peluquería y otros tratamientos de belleza" },
    { codigo: "96030", descripcion: "Pompas fúnebres y actividades conexas" },
    { codigo: "96090", descripcion: "Otras actividades de servicios personales n.c.p." },

    // Actividades de los hogares (97-98)
    { codigo: "97000", descripcion: "Actividades de los hogares como empleadores de personal doméstico" },
    { codigo: "98100", descripcion: "Actividades no diferenciadas de los hogares como productores de bienes para uso propio" },
    { codigo: "98200", descripcion: "Actividades no diferenciadas de los hogares como productores de servicios para uso propio" },

    // Actividades de organizaciones y órganos extraterritoriales (99)
    { codigo: "99000", descripcion: "Actividades de organizaciones y órganos extraterritoriales" },
];

export function getActividadByCodigo(codigo: string): ActividadEconomica | undefined {
    return actividades.find((a) => a.codigo === codigo);
}

export function getActividadDescripcion(codigo: string): string {
    return getActividadByCodigo(codigo)?.descripcion || "";
}

export function buscarActividades(termino: string): ActividadEconomica[] {
    const term = termino.toLowerCase();
    return actividades.filter(
        (a) => a.codigo.includes(term) || a.descripcion.toLowerCase().includes(term)
    );
}
