// CAT-013: Municipios de El Salvador
// Fuente: Ministerio de Hacienda - DGII

export interface Municipio {
    codigo: string;
    nombre: string;
    departamento: string; // Código del departamento
}

export const municipios: Municipio[] = [
    // 01 - Ahuachapán (12 municipios)
    { codigo: "01", nombre: "Ahuachapán", departamento: "01" },
    { codigo: "02", nombre: "Apaneca", departamento: "01" },
    { codigo: "03", nombre: "Atiquizaya", departamento: "01" },
    { codigo: "04", nombre: "Concepción de Ataco", departamento: "01" },
    { codigo: "05", nombre: "El Refugio", departamento: "01" },
    { codigo: "06", nombre: "Guaymango", departamento: "01" },
    { codigo: "07", nombre: "Jujutla", departamento: "01" },
    { codigo: "08", nombre: "San Francisco Menéndez", departamento: "01" },
    { codigo: "09", nombre: "San Lorenzo", departamento: "01" },
    { codigo: "10", nombre: "San Pedro Puxtla", departamento: "01" },
    { codigo: "11", nombre: "Tacuba", departamento: "01" },
    { codigo: "12", nombre: "Turín", departamento: "01" },

    // 02 - Santa Ana (13 municipios)
    { codigo: "01", nombre: "Candelaria de la Frontera", departamento: "02" },
    { codigo: "02", nombre: "Chalchuapa", departamento: "02" },
    { codigo: "03", nombre: "Coatepeque", departamento: "02" },
    { codigo: "04", nombre: "El Congo", departamento: "02" },
    { codigo: "05", nombre: "El Porvenir", departamento: "02" },
    { codigo: "06", nombre: "Masahuat", departamento: "02" },
    { codigo: "07", nombre: "Metapán", departamento: "02" },
    { codigo: "08", nombre: "San Antonio Pajonal", departamento: "02" },
    { codigo: "09", nombre: "San Sebastián Salitrillo", departamento: "02" },
    { codigo: "10", nombre: "Santa Ana", departamento: "02" },
    { codigo: "11", nombre: "Santa Rosa Guachipilín", departamento: "02" },
    { codigo: "12", nombre: "Santiago de la Frontera", departamento: "02" },
    { codigo: "13", nombre: "Texistepeque", departamento: "02" },

    // 03 - Sonsonate (16 municipios)
    { codigo: "01", nombre: "Acajutla", departamento: "03" },
    { codigo: "02", nombre: "Armenia", departamento: "03" },
    { codigo: "03", nombre: "Caluco", departamento: "03" },
    { codigo: "04", nombre: "Cuisnahuat", departamento: "03" },
    { codigo: "05", nombre: "Izalco", departamento: "03" },
    { codigo: "06", nombre: "Juayúa", departamento: "03" },
    { codigo: "07", nombre: "Nahuizalco", departamento: "03" },
    { codigo: "08", nombre: "Nahulingo", departamento: "03" },
    { codigo: "09", nombre: "Salcoatitán", departamento: "03" },
    { codigo: "10", nombre: "San Antonio del Monte", departamento: "03" },
    { codigo: "11", nombre: "San Julián", departamento: "03" },
    { codigo: "12", nombre: "Santa Catarina Masahuat", departamento: "03" },
    { codigo: "13", nombre: "Santa Isabel Ishuatán", departamento: "03" },
    { codigo: "14", nombre: "Santo Domingo de Guzmán", departamento: "03" },
    { codigo: "15", nombre: "Sonsonate", departamento: "03" },
    { codigo: "16", nombre: "Sonzacate", departamento: "03" },

    // 04 - Chalatenango (33 municipios)
    { codigo: "01", nombre: "Agua Caliente", departamento: "04" },
    { codigo: "02", nombre: "Arcatao", departamento: "04" },
    { codigo: "03", nombre: "Azacualpa", departamento: "04" },
    { codigo: "04", nombre: "Cancasque", departamento: "04" },
    { codigo: "05", nombre: "Chalatenango", departamento: "04" },
    { codigo: "06", nombre: "Citalá", departamento: "04" },
    { codigo: "07", nombre: "Comalapa", departamento: "04" },
    { codigo: "08", nombre: "Concepción Quezaltepeque", departamento: "04" },
    { codigo: "09", nombre: "Dulce Nombre de María", departamento: "04" },
    { codigo: "10", nombre: "El Carrizal", departamento: "04" },
    { codigo: "11", nombre: "El Paraíso", departamento: "04" },
    { codigo: "12", nombre: "La Laguna", departamento: "04" },
    { codigo: "13", nombre: "La Palma", departamento: "04" },
    { codigo: "14", nombre: "La Reina", departamento: "04" },
    { codigo: "15", nombre: "Las Vueltas", departamento: "04" },
    { codigo: "16", nombre: "Nombre de Jesús", departamento: "04" },
    { codigo: "17", nombre: "Nueva Concepción", departamento: "04" },
    { codigo: "18", nombre: "Nueva Trinidad", departamento: "04" },
    { codigo: "19", nombre: "Ojos de Agua", departamento: "04" },
    { codigo: "20", nombre: "Potonico", departamento: "04" },
    { codigo: "21", nombre: "San Antonio de la Cruz", departamento: "04" },
    { codigo: "22", nombre: "San Antonio Los Ranchos", departamento: "04" },
    { codigo: "23", nombre: "San Fernando", departamento: "04" },
    { codigo: "24", nombre: "San Francisco Lempa", departamento: "04" },
    { codigo: "25", nombre: "San Francisco Morazán", departamento: "04" },
    { codigo: "26", nombre: "San Ignacio", departamento: "04" },
    { codigo: "27", nombre: "San Isidro Labrador", departamento: "04" },
    { codigo: "28", nombre: "San Luis del Carmen", departamento: "04" },
    { codigo: "29", nombre: "San Miguel de Mercedes", departamento: "04" },
    { codigo: "30", nombre: "San Rafael", departamento: "04" },
    { codigo: "31", nombre: "Santa Rita", departamento: "04" },
    { codigo: "32", nombre: "Tejutla", departamento: "04" },
    { codigo: "33", nombre: "Las Flores", departamento: "04" },

    // 05 - La Libertad (22 municipios)
    { codigo: "01", nombre: "Antiguo Cuscatlán", departamento: "05" },
    { codigo: "02", nombre: "Chiltiupán", departamento: "05" },
    { codigo: "03", nombre: "Ciudad Arce", departamento: "05" },
    { codigo: "04", nombre: "Colón", departamento: "05" },
    { codigo: "05", nombre: "Comasagua", departamento: "05" },
    { codigo: "06", nombre: "Huizúcar", departamento: "05" },
    { codigo: "07", nombre: "Jayaque", departamento: "05" },
    { codigo: "08", nombre: "Jicalapa", departamento: "05" },
    { codigo: "09", nombre: "La Libertad", departamento: "05" },
    { codigo: "10", nombre: "Nuevo Cuscatlán", departamento: "05" },
    { codigo: "11", nombre: "Santa Tecla", departamento: "05" },
    { codigo: "12", nombre: "Quezaltepeque", departamento: "05" },
    { codigo: "13", nombre: "Sacacoyo", departamento: "05" },
    { codigo: "14", nombre: "San José Villanueva", departamento: "05" },
    { codigo: "15", nombre: "San Juan Opico", departamento: "05" },
    { codigo: "16", nombre: "San Matías", departamento: "05" },
    { codigo: "17", nombre: "San Pablo Tacachico", departamento: "05" },
    { codigo: "18", nombre: "Talnique", departamento: "05" },
    { codigo: "19", nombre: "Tamanique", departamento: "05" },
    { codigo: "20", nombre: "Teotepeque", departamento: "05" },
    { codigo: "21", nombre: "Tepecoyo", departamento: "05" },
    { codigo: "22", nombre: "Zaragoza", departamento: "05" },

    // 06 - San Salvador (19 municipios)
    { codigo: "01", nombre: "Aguilares", departamento: "06" },
    { codigo: "02", nombre: "Apopa", departamento: "06" },
    { codigo: "03", nombre: "Ayutuxtepeque", departamento: "06" },
    { codigo: "04", nombre: "Cuscatancingo", departamento: "06" },
    { codigo: "05", nombre: "Ciudad Delgado", departamento: "06" },
    { codigo: "06", nombre: "El Paisnal", departamento: "06" },
    { codigo: "07", nombre: "Guazapa", departamento: "06" },
    { codigo: "08", nombre: "Ilopango", departamento: "06" },
    { codigo: "09", nombre: "Mejicanos", departamento: "06" },
    { codigo: "10", nombre: "Nejapa", departamento: "06" },
    { codigo: "11", nombre: "Panchimalco", departamento: "06" },
    { codigo: "12", nombre: "Rosario de Mora", departamento: "06" },
    { codigo: "13", nombre: "San Marcos", departamento: "06" },
    { codigo: "14", nombre: "San Martín", departamento: "06" },
    { codigo: "15", nombre: "San Salvador", departamento: "06" },
    { codigo: "16", nombre: "Santiago Texacuangos", departamento: "06" },
    { codigo: "17", nombre: "Santo Tomás", departamento: "06" },
    { codigo: "18", nombre: "Soyapango", departamento: "06" },
    { codigo: "19", nombre: "Tonacatepeque", departamento: "06" },

    // 07 - Cuscatlán (16 municipios)
    { codigo: "01", nombre: "Candelaria", departamento: "07" },
    { codigo: "02", nombre: "Cojutepeque", departamento: "07" },
    { codigo: "03", nombre: "El Carmen", departamento: "07" },
    { codigo: "04", nombre: "El Rosario", departamento: "07" },
    { codigo: "05", nombre: "Monte San Juan", departamento: "07" },
    { codigo: "06", nombre: "Oratorio de Concepción", departamento: "07" },
    { codigo: "07", nombre: "San Bartolomé Perulapía", departamento: "07" },
    { codigo: "08", nombre: "San Cristóbal", departamento: "07" },
    { codigo: "09", nombre: "San José Guayabal", departamento: "07" },
    { codigo: "10", nombre: "San Pedro Perulapán", departamento: "07" },
    { codigo: "11", nombre: "San Rafael Cedros", departamento: "07" },
    { codigo: "12", nombre: "San Ramón", departamento: "07" },
    { codigo: "13", nombre: "Santa Cruz Analquito", departamento: "07" },
    { codigo: "14", nombre: "Santa Cruz Michapa", departamento: "07" },
    { codigo: "15", nombre: "Suchitoto", departamento: "07" },
    { codigo: "16", nombre: "Tenancingo", departamento: "07" },

    // 08 - La Paz (22 municipios)
    { codigo: "01", nombre: "Cuyultitán", departamento: "08" },
    { codigo: "02", nombre: "El Rosario", departamento: "08" },
    { codigo: "03", nombre: "Jerusalén", departamento: "08" },
    { codigo: "04", nombre: "Mercedes La Ceiba", departamento: "08" },
    { codigo: "05", nombre: "Olocuilta", departamento: "08" },
    { codigo: "06", nombre: "Paraíso de Osorio", departamento: "08" },
    { codigo: "07", nombre: "San Antonio Masahuat", departamento: "08" },
    { codigo: "08", nombre: "San Emigdio", departamento: "08" },
    { codigo: "09", nombre: "San Francisco Chinameca", departamento: "08" },
    { codigo: "10", nombre: "San Juan Nonualco", departamento: "08" },
    { codigo: "11", nombre: "San Juan Talpa", departamento: "08" },
    { codigo: "12", nombre: "San Juan Tepezontes", departamento: "08" },
    { codigo: "13", nombre: "San Luis La Herradura", departamento: "08" },
    { codigo: "14", nombre: "San Luis Talpa", departamento: "08" },
    { codigo: "15", nombre: "San Miguel Tepezontes", departamento: "08" },
    { codigo: "16", nombre: "San Pedro Masahuat", departamento: "08" },
    { codigo: "17", nombre: "San Pedro Nonualco", departamento: "08" },
    { codigo: "18", nombre: "San Rafael Obrajuelo", departamento: "08" },
    { codigo: "19", nombre: "Santa María Ostuma", departamento: "08" },
    { codigo: "20", nombre: "Santiago Nonualco", departamento: "08" },
    { codigo: "21", nombre: "Tapalhuaca", departamento: "08" },
    { codigo: "22", nombre: "Zacatecoluca", departamento: "08" },

    // 09 - Cabañas (9 municipios)
    { codigo: "01", nombre: "Cinquera", departamento: "09" },
    { codigo: "02", nombre: "Dolores", departamento: "09" },
    { codigo: "03", nombre: "Guacotecti", departamento: "09" },
    { codigo: "04", nombre: "Ilobasco", departamento: "09" },
    { codigo: "05", nombre: "Jutiapa", departamento: "09" },
    { codigo: "06", nombre: "San Isidro", departamento: "09" },
    { codigo: "07", nombre: "Sensuntepeque", departamento: "09" },
    { codigo: "08", nombre: "Tejutepeque", departamento: "09" },
    { codigo: "09", nombre: "Victoria", departamento: "09" },

    // 10 - San Vicente (13 municipios)
    { codigo: "01", nombre: "Apastepeque", departamento: "10" },
    { codigo: "02", nombre: "Guadalupe", departamento: "10" },
    { codigo: "03", nombre: "San Cayetano Istepeque", departamento: "10" },
    { codigo: "04", nombre: "San Esteban Catarina", departamento: "10" },
    { codigo: "05", nombre: "San Ildefonso", departamento: "10" },
    { codigo: "06", nombre: "San Lorenzo", departamento: "10" },
    { codigo: "07", nombre: "San Sebastián", departamento: "10" },
    { codigo: "08", nombre: "San Vicente", departamento: "10" },
    { codigo: "09", nombre: "Santa Clara", departamento: "10" },
    { codigo: "10", nombre: "Santo Domingo", departamento: "10" },
    { codigo: "11", nombre: "Tecoluca", departamento: "10" },
    { codigo: "12", nombre: "Tepetitán", departamento: "10" },
    { codigo: "13", nombre: "Verapaz", departamento: "10" },

    // 11 - Usulután (23 municipios)
    { codigo: "01", nombre: "Alegría", departamento: "11" },
    { codigo: "02", nombre: "Berlín", departamento: "11" },
    { codigo: "03", nombre: "California", departamento: "11" },
    { codigo: "04", nombre: "Concepción Batres", departamento: "11" },
    { codigo: "05", nombre: "El Triunfo", departamento: "11" },
    { codigo: "06", nombre: "Ereguayquín", departamento: "11" },
    { codigo: "07", nombre: "Estanzuelas", departamento: "11" },
    { codigo: "08", nombre: "Jiquilisco", departamento: "11" },
    { codigo: "09", nombre: "Jucuapa", departamento: "11" },
    { codigo: "10", nombre: "Jucuarán", departamento: "11" },
    { codigo: "11", nombre: "Mercedes Umaña", departamento: "11" },
    { codigo: "12", nombre: "Nueva Granada", departamento: "11" },
    { codigo: "13", nombre: "Ozatlán", departamento: "11" },
    { codigo: "14", nombre: "Puerto El Triunfo", departamento: "11" },
    { codigo: "15", nombre: "San Agustín", departamento: "11" },
    { codigo: "16", nombre: "San Buenaventura", departamento: "11" },
    { codigo: "17", nombre: "San Dionisio", departamento: "11" },
    { codigo: "18", nombre: "San Francisco Javier", departamento: "11" },
    { codigo: "19", nombre: "Santa Elena", departamento: "11" },
    { codigo: "20", nombre: "Santa María", departamento: "11" },
    { codigo: "21", nombre: "Santiago de María", departamento: "11" },
    { codigo: "22", nombre: "Tecapán", departamento: "11" },
    { codigo: "23", nombre: "Usulután", departamento: "11" },

    // 12 - San Miguel (20 municipios)
    { codigo: "01", nombre: "Carolina", departamento: "12" },
    { codigo: "02", nombre: "Chapeltique", departamento: "12" },
    { codigo: "03", nombre: "Chinameca", departamento: "12" },
    { codigo: "04", nombre: "Chirilagua", departamento: "12" },
    { codigo: "05", nombre: "Ciudad Barrios", departamento: "12" },
    { codigo: "06", nombre: "Comacarán", departamento: "12" },
    { codigo: "07", nombre: "El Tránsito", departamento: "12" },
    { codigo: "08", nombre: "Lolotique", departamento: "12" },
    { codigo: "09", nombre: "Moncagua", departamento: "12" },
    { codigo: "10", nombre: "Nueva Guadalupe", departamento: "12" },
    { codigo: "11", nombre: "Nuevo Edén de San Juan", departamento: "12" },
    { codigo: "12", nombre: "Quelepa", departamento: "12" },
    { codigo: "13", nombre: "San Antonio", departamento: "12" },
    { codigo: "14", nombre: "San Gerardo", departamento: "12" },
    { codigo: "15", nombre: "San Jorge", departamento: "12" },
    { codigo: "16", nombre: "San Luis de la Reina", departamento: "12" },
    { codigo: "17", nombre: "San Miguel", departamento: "12" },
    { codigo: "18", nombre: "San Rafael Oriente", departamento: "12" },
    { codigo: "19", nombre: "Sesori", departamento: "12" },
    { codigo: "20", nombre: "Uluazapa", departamento: "12" },

    // 13 - Morazán (26 municipios)
    { codigo: "01", nombre: "Arambala", departamento: "13" },
    { codigo: "02", nombre: "Cacaopera", departamento: "13" },
    { codigo: "03", nombre: "Chilanga", departamento: "13" },
    { codigo: "04", nombre: "Corinto", departamento: "13" },
    { codigo: "05", nombre: "Delicias de Concepción", departamento: "13" },
    { codigo: "06", nombre: "El Divisadero", departamento: "13" },
    { codigo: "07", nombre: "El Rosario", departamento: "13" },
    { codigo: "08", nombre: "Gualococti", departamento: "13" },
    { codigo: "09", nombre: "Guatajiagua", departamento: "13" },
    { codigo: "10", nombre: "Joateca", departamento: "13" },
    { codigo: "11", nombre: "Jocoaitique", departamento: "13" },
    { codigo: "12", nombre: "Jocoro", departamento: "13" },
    { codigo: "13", nombre: "Lolotiquillo", departamento: "13" },
    { codigo: "14", nombre: "Meanguera", departamento: "13" },
    { codigo: "15", nombre: "Osicala", departamento: "13" },
    { codigo: "16", nombre: "Perquín", departamento: "13" },
    { codigo: "17", nombre: "San Carlos", departamento: "13" },
    { codigo: "18", nombre: "San Fernando", departamento: "13" },
    { codigo: "19", nombre: "San Francisco Gotera", departamento: "13" },
    { codigo: "20", nombre: "San Isidro", departamento: "13" },
    { codigo: "21", nombre: "San Simón", departamento: "13" },
    { codigo: "22", nombre: "Sensembra", departamento: "13" },
    { codigo: "23", nombre: "Sociedad", departamento: "13" },
    { codigo: "24", nombre: "Torola", departamento: "13" },
    { codigo: "25", nombre: "Yamabal", departamento: "13" },
    { codigo: "26", nombre: "Yoloaiquín", departamento: "13" },

    // 14 - La Unión (18 municipios)
    { codigo: "01", nombre: "Anamorós", departamento: "14" },
    { codigo: "02", nombre: "Bolívar", departamento: "14" },
    { codigo: "03", nombre: "Concepción de Oriente", departamento: "14" },
    { codigo: "04", nombre: "Conchagua", departamento: "14" },
    { codigo: "05", nombre: "El Carmen", departamento: "14" },
    { codigo: "06", nombre: "El Sauce", departamento: "14" },
    { codigo: "07", nombre: "Intipucá", departamento: "14" },
    { codigo: "08", nombre: "La Unión", departamento: "14" },
    { codigo: "09", nombre: "Lilisque", departamento: "14" },
    { codigo: "10", nombre: "Meanguera del Golfo", departamento: "14" },
    { codigo: "11", nombre: "Nueva Esparta", departamento: "14" },
    { codigo: "12", nombre: "Pasaquina", departamento: "14" },
    { codigo: "13", nombre: "Polorós", departamento: "14" },
    { codigo: "14", nombre: "San Alejo", departamento: "14" },
    { codigo: "15", nombre: "San José", departamento: "14" },
    { codigo: "16", nombre: "Santa Rosa de Lima", departamento: "14" },
    { codigo: "17", nombre: "Yayantique", departamento: "14" },
    { codigo: "18", nombre: "Yucuaiquín", departamento: "14" },
];

export function getMunicipiosByDepartamento(departamento: string): Municipio[] {
    return municipios.filter((m) => m.departamento === departamento);
}

export function getMunicipio(departamento: string, municipio: string): Municipio | undefined {
    return municipios.find((m) => m.departamento === departamento && m.codigo === municipio);
}

export function getMunicipioNombre(departamento: string, municipio: string): string {
    return getMunicipio(departamento, municipio)?.nombre || "";
}
